name: Check and Test Python Project

on:
  workflow_dispatch:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0 # for SonarQube coverage report

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true

      - name: Python set up
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - name: Run pytest unittests
        run: |
          uv run --frozen pytest tests/ --cov --cov-report=xml:coverage.xml

      - name: Run pre-commit hooks
        uses: pre-commit/action@v3.0.1

      # for SonarQube coverage report
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      # - name: Minimize uv cache
      #   run: uv cache prune --ci
